export const productItems = [
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
  {
    id: 1,
    title: "Product title",
    price: 20.5,
    description: "Product description",
    category: "Product category",
    image: "Product image url",
  },
];
